import { Prop, Schema, SchemaFactory } from "@nestjs/mongoose";
import { Document, Types } from "mongoose";

export type MessageDocument = Message & Document;

// For Phase 6 (Attachments)
class MessageAttachment {
  @Prop({ required: true })
  fileKey!: string; // MinIO path

  @Prop({ required: true })
  mimeType!: string;

  @Prop({ required: true })
  fileName!: string;
}

@Schema({ timestamps: true })
export class Message {
  // 🛡️ THE IDEMPOTENCY SHIELD
  // Generated by the Frontend (UUIDv7) BEFORE sending via WebSocket/HTTP.
  @Prop({ required: true, unique: true })
  clientMessageId!: string;

  @Prop({
    type: Types.ObjectId,
    required: true,
    ref: "Conversation",
    index: true,
  })
  conversationId!: Types.ObjectId;

  @Prop({ required: true, index: true })
  senderId!: string; // actorId

  @Prop({ required: false })
  content?: string; // Optional because a message might just be an image attachment

  @Prop({ type: [MessageAttachment], default: [] })
  attachments!: MessageAttachment[];

  // System flags
  @Prop({ default: false })
  isDeleted!: boolean; // Soft delete ("This message was deleted")

  @Prop({ default: false })
  isEdited!: boolean; // Flag to show "Edited" in the UI

  createdAt!: Date; // Auto-managed by Mongoose
  updatedAt!: Date; // Auto-managed by Mongoose
}

export const MessageSchema = SchemaFactory.createForClass(Message);

// ✨ CURSOR PAGINATION INDEX
// When loading chat history, we always query by conversationId and sort by createdAt DESC.
// This compound index makes that query execute in O(1) time.
MessageSchema.index({ conversationId: 1, createdAt: -1 });
