# Node modules (we install them inside container)
**/node_modules

# Local build artifacts
**/dist

# Mobile app build artifacts
**/android
**/ios

# Capacitor build artifacts
**/capacitor

# Environment files (for secrets, use env_file in compose)
**/.env
**/*.env.*

# Git files
**/.git
**/.gitignore

# Docker / system files
**/Dockerfile*
**/docker-compose*.yml

# IDE / editor files
**/.vscode
**/.idea
**/*.swp

# OS files
**/.DS_Store
**/Thumbs.db