global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  # Scrape configuration for the identity service
  - job_name: "identity-service"
    static_configs:
      # Use the exact container name and the internal Docker port
      - targets: ["decp-identity-service:4000"]

  # Scrape configuration for the engagement service
  - job_name: "engagement-service"
    static_configs:
      # Use the exact container name and the internal Docker port
      - targets: ["decp-engagement-service:4001"]

  # Scrape configuration for the career service
  - job_name: "career-service"
    static_configs:
      # Use the exact container name and the internal Docker port
      - targets: ["decp-career-service:4002"]

  # Scrape configuration for the event service
  - job_name: "event-service"
    static_configs:
      # Use the exact container name and the internal Docker port
      - targets: ["decp-event-service:4003"]

  # Scrape configuration for the collaboration service
  - job_name: "collaboration-service"
    static_configs:
      # Use the exact container name and the internal Docker port
      - targets: ["decp-collab-service:4004"]

  # Scrape configuration for the message service
  - job_name: "message-service"
    static_configs:
      # Use the exact container name and the internal Docker port
      - targets: ["decp-message-service:4005"]

  # Scrape configuration for the notification service
  - job_name: "notification-service"
    static_configs:
      # Use the exact container name and the internal Docker port
      - targets: ["decp-notification-service:4006"]

  # Scrape configuration for the analytics service
  - job_name: "analytics-service"
    static_configs:
      # Use the exact container name and the internal Docker port
      - targets: ["decp-analytics-service:4007"]
