receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317" # ✨ The Fix: Listen to the whole Docker network
      http:
        endpoint: "0.0.0.0:4318" # ✨ The Fix: Listen to the whole Docker network

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: "0.0.0.0:8889"

  elasticsearch:
    endpoints: ["http://decp-elasticsearch:9200"]
    logs_index: "otel-logs"
    traces_index: "otel-traces"
    metrics_index: "otel-metrics"
    mapping:
      mode: "ecs"
    tls:
      insecure: true

processors:
  batch:
    timeout: 10s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, elasticsearch]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, debug]
